import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter_sound/flutter_sound.dart' as fs;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;
import 'package:record/record.dart';
import 'package:audio_session/audio_session.dart';

import '../../app/constants/runtime.dart';
import '../../app/constants/storage.dart';
import '../../app/config.dart';
import '../../app/navigator.dart';
import '../../app/routes.dart';
import '../../data/models.dart';
import '../api_client.dart';
import '../cache/loader.dart';
import '../cache/local.dart';
import '../currency.dart';
import '../preview.dart';
import '../startup/cues.dart';
import '../token_store.dart';
import '../validators.dart';

part 'service.dart';
part 'overlay.dart';
part 'socket/connection.dart';
part 'socket/replay.dart';
part 'socket/messages.dart';
part 'socket/capture.dart';
part 'tools.dart';
part 'draft/shared.dart';
part 'draft/state.dart';
part 'draft/customer.dart';
part 'draft/mutations.dart';
part 'draft/storage.dart';
part 'draft/requirements.dart';
part 'draft/reports.dart';
part 'draft/routes.dart';
part 'templates/models.dart';
part 'templates/common.dart';
part 'templates/builder.dart';
part 'templates/customer.dart';
part 'templates/item.dart';
part 'templates/sales.dart';
part 'templates/receipts.dart';
part 'templates/invoice.dart';
part 'templates/widgets.dart';
part 'widgets.dart';
