ALTER TABLE shops
ADD COLUMN IF NOT EXISTS currency_code TEXT;

UPDATE shops
SET currency_code = CASE
    WHEN phone LIKE '+234%' THEN 'NGN'
    WHEN phone LIKE '+233%' THEN 'GHS'
    WHEN phone LIKE '+254%' THEN 'KES'
    WHEN phone LIKE '+255%' THEN 'TZS'
    WHEN phone LIKE '+256%' THEN 'UGX'
    WHEN phone LIKE '+250%' THEN 'RWF'
    WHEN phone LIKE '+251%' THEN 'ETB'
    WHEN phone LIKE '+27%' THEN 'ZAR'
    WHEN phone LIKE '+20%' THEN 'EGP'
    WHEN phone LIKE '+212%' THEN 'MAD'
    WHEN phone LIKE '+213%' THEN 'DZD'
    WHEN phone LIKE '+216%' THEN 'TND'
    WHEN phone LIKE '+218%' THEN 'LYD'
    WHEN phone LIKE '+221%' THEN 'XOF'
    WHEN phone LIKE '+222%' THEN 'MRU'
    WHEN phone LIKE '+223%' THEN 'XOF'
    WHEN phone LIKE '+224%' THEN 'GNF'
    WHEN phone LIKE '+225%' THEN 'XOF'
    WHEN phone LIKE '+226%' THEN 'XOF'
    WHEN phone LIKE '+227%' THEN 'XOF'
    WHEN phone LIKE '+228%' THEN 'XOF'
    WHEN phone LIKE '+229%' THEN 'XOF'
    WHEN phone LIKE '+230%' THEN 'MUR'
    WHEN phone LIKE '+231%' THEN 'LRD'
    WHEN phone LIKE '+232%' THEN 'SLL'
    WHEN phone LIKE '+237%' THEN 'XAF'
    WHEN phone LIKE '+240%' THEN 'XAF'
    WHEN phone LIKE '+241%' THEN 'XAF'
    WHEN phone LIKE '+242%' THEN 'XAF'
    WHEN phone LIKE '+243%' THEN 'CDF'
    WHEN phone LIKE '+244%' THEN 'AOA'
    WHEN phone LIKE '+249%' THEN 'SDG'
    WHEN phone LIKE '+44%' THEN 'GBP'
    WHEN phone LIKE '+1%' THEN 'USD'
    WHEN phone LIKE '+33%' THEN 'EUR'
    WHEN phone LIKE '+34%' THEN 'EUR'
    WHEN phone LIKE '+39%' THEN 'EUR'
    WHEN phone LIKE '+49%' THEN 'EUR'
    WHEN phone LIKE '+31%' THEN 'EUR'
    WHEN phone LIKE '+32%' THEN 'EUR'
    WHEN phone LIKE '+351%' THEN 'EUR'
    WHEN phone LIKE '+353%' THEN 'EUR'
    WHEN phone LIKE '+41%' THEN 'CHF'
    WHEN phone LIKE '+45%' THEN 'DKK'
    WHEN phone LIKE '+46%' THEN 'SEK'
    WHEN phone LIKE '+47%' THEN 'NOK'
    WHEN phone LIKE '+48%' THEN 'PLN'
    WHEN phone LIKE '+40%' THEN 'RON'
    WHEN phone LIKE '+420%' THEN 'CZK'
    WHEN phone LIKE '+421%' THEN 'EUR'
    WHEN phone LIKE '+7%' THEN 'RUB'
    WHEN phone LIKE '+90%' THEN 'TRY'
    WHEN phone LIKE '+91%' THEN 'INR'
    WHEN phone LIKE '+92%' THEN 'PKR'
    WHEN phone LIKE '+94%' THEN 'LKR'
    WHEN phone LIKE '+98%' THEN 'IRR'
    WHEN phone LIKE '+234%' THEN 'NGN'
    WHEN phone LIKE '+60%' THEN 'MYR'
    WHEN phone LIKE '+61%' THEN 'AUD'
    WHEN phone LIKE '+62%' THEN 'IDR'
    WHEN phone LIKE '+63%' THEN 'PHP'
    WHEN phone LIKE '+64%' THEN 'NZD'
    WHEN phone LIKE '+65%' THEN 'SGD'
    WHEN phone LIKE '+66%' THEN 'THB'
    WHEN phone LIKE '+81%' THEN 'JPY'
    WHEN phone LIKE '+82%' THEN 'KRW'
    WHEN phone LIKE '+84%' THEN 'VND'
    WHEN phone LIKE '+86%' THEN 'CNY'
    WHEN phone LIKE '+852%' THEN 'HKD'
    WHEN phone LIKE '+855%' THEN 'KHR'
    WHEN phone LIKE '+856%' THEN 'LAK'
    WHEN phone LIKE '+880%' THEN 'BDT'
    WHEN phone LIKE '+886%' THEN 'TWD'
    WHEN phone LIKE '+971%' THEN 'AED'
    WHEN phone LIKE '+966%' THEN 'SAR'
    WHEN phone LIKE '+973%' THEN 'BHD'
    WHEN phone LIKE '+974%' THEN 'QAR'
    WHEN phone LIKE '+965%' THEN 'KWD'
    WHEN phone LIKE '+968%' THEN 'OMR'
    WHEN phone LIKE '+962%' THEN 'JOD'
    WHEN phone LIKE '+52%' THEN 'MXN'
    WHEN phone LIKE '+54%' THEN 'ARS'
    WHEN phone LIKE '+55%' THEN 'BRL'
    WHEN phone LIKE '+56%' THEN 'CLP'
    WHEN phone LIKE '+57%' THEN 'COP'
    WHEN phone LIKE '+58%' THEN 'VES'
    WHEN phone LIKE '+51%' THEN 'PEN'
    WHEN phone LIKE '+591%' THEN 'BOB'
    WHEN phone LIKE '+593%' THEN 'USD'
    WHEN phone LIKE '+595%' THEN 'PYG'
    WHEN phone LIKE '+598%' THEN 'UYU'
    WHEN phone LIKE '+502%' THEN 'GTQ'
    WHEN phone LIKE '+503%' THEN 'USD'
    WHEN phone LIKE '+504%' THEN 'HNL'
    WHEN phone LIKE '+505%' THEN 'NIO'
    WHEN phone LIKE '+506%' THEN 'CRC'
    WHEN phone LIKE '+507%' THEN 'USD'
    ELSE 'NGN'
END
WHERE currency_code IS NULL OR btrim(currency_code) = '';

ALTER TABLE shops
ALTER COLUMN currency_code SET DEFAULT 'NGN';

UPDATE shops
SET currency_code = 'NGN'
WHERE currency_code IS NULL OR btrim(currency_code) = '';

ALTER TABLE shops
ALTER COLUMN currency_code SET NOT NULL;
