ALTER TABLE shops
ADD COLUMN IF NOT EXISTS live_agent_subscription_active BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS live_agent_tokens_used BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS live_agent_tokens_available BIGINT NOT NULL DEFAULT 3000000;
