import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui';

import 'package:flutter_sound/flutter_sound.dart' as fs;
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:image_picker/image_picker.dart';
import 'package:record/record.dart';

import '../app/config.dart';
import '../app/navigator.dart';
import '../app/routes.dart';
import '../data/models.dart';
import 'api_client.dart';
import 'cache/loader.dart';
import 'cache/local.dart';
import 'currency.dart';
import 'token_store.dart';
import 'validators.dart';

part 'live_cashier/service.dart';
part 'live_cashier/overlay.dart';
part 'live_cashier/socket.dart';
part 'live_cashier/tools.dart';
part 'live_cashier/draft/shared.dart';
part 'live_cashier/draft/state.dart';
part 'live_cashier/draft/customer.dart';
part 'live_cashier/draft/mutations.dart';
part 'live_cashier/draft/storage.dart';
part 'live_cashier/draft/requirements.dart';
part 'live_cashier/draft/reports.dart';
part 'live_cashier/draft/routes.dart';
part 'live_cashier/templates/models.dart';
part 'live_cashier/templates/common.dart';
part 'live_cashier/templates/builder.dart';
part 'live_cashier/templates/customer.dart';
part 'live_cashier/templates/item.dart';
part 'live_cashier/templates/receipts.dart';
part 'live_cashier/templates/invoice.dart';
part 'live_cashier/templates/widgets.dart';
part 'live_cashier/widgets.dart';
